// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PROJECT_BINJA_H_
#define FLATBUFFERS_GENERATED_PROJECT_BINJA_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace binja {

struct Project;
struct ProjectBuilder;

struct Project FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ProjectBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERSION = 4
  };
  uint32_t version() const {
    return GetField<uint32_t>(VT_VERSION, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_VERSION, 4) &&
           verifier.EndTable();
  }
};

struct ProjectBuilder {
  typedef Project Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_version(uint32_t version) {
    fbb_.AddElement<uint32_t>(Project::VT_VERSION, version, 0);
  }
  explicit ProjectBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Project> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Project>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Project> CreateProject(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t version = 0) {
  ProjectBuilder builder_(_fbb);
  builder_.add_version(version);
  return builder_.Finish();
}

inline const binja::Project *GetProject(const void *buf) {
  return ::flatbuffers::GetRoot<binja::Project>(buf);
}

inline const binja::Project *GetSizePrefixedProject(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<binja::Project>(buf);
}

template <bool B = false>
inline bool VerifyProjectBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<binja::Project>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedProjectBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<binja::Project>(nullptr);
}

inline void FinishProjectBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<binja::Project> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedProjectBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<binja::Project> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace binja

#endif  // FLATBUFFERS_GENERATED_PROJECT_BINJA_H_
